// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaqXotc1n8E1sdwVD3MEIJyJZlA83r13M',
    appId: '1:145139544944:web:1e89622bae17be833355b5',
    messagingSenderId: '145139544944',
    projectId: 'money-bhai-470c2',
    authDomain: 'money-bhai-470c2.firebaseapp.com',
    storageBucket: 'money-bhai-470c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIS6YbA6nT-dCCIVRGPQnCeLBz4HQOBkY',
    appId: '1:145139544944:android:4ff4035bb97d77473355b5',
    messagingSenderId: '145139544944',
    projectId: 'money-bhai-470c2',
    storageBucket: 'money-bhai-470c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-_QYydUYtI8j6EhaVhE7jySG2yHnM52w',
    appId: '1:145139544944:ios:9a6d8655f4c046f53355b5',
    messagingSenderId: '145139544944',
    projectId: 'money-bhai-470c2',
    storageBucket: 'money-bhai-470c2.firebasestorage.app',
    iosBundleId: 'com.example.moneyBhai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-_QYydUYtI8j6EhaVhE7jySG2yHnM52w',
    appId: '1:145139544944:ios:9a6d8655f4c046f53355b5',
    messagingSenderId: '145139544944',
    projectId: 'money-bhai-470c2',
    storageBucket: 'money-bhai-470c2.firebasestorage.app',
    iosBundleId: 'com.example.moneyBhai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaqXotc1n8E1sdwVD3MEIJyJZlA83r13M',
    appId: '1:145139544944:web:bf13ce81f1ac36443355b5',
    messagingSenderId: '145139544944',
    projectId: 'money-bhai-470c2',
    authDomain: 'money-bhai-470c2.firebaseapp.com',
    storageBucket: 'money-bhai-470c2.firebasestorage.app',
  );
}
